plugins {
    id 'com.android.application'
}

android {
    namespace 'ma.kaynmaytkal.app'
    compileSdk 36

    defaultConfig {
        applicationId 'ma.kaynmaytkal.app'
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
